### ISSUE TITLE
OpenCV/GStreamer/ Rk3399

### ISSUE THREAD

**Issue by ayaromenok** [ayaromenok/test#9]
Since many people came to this issue with Rk3399 camera questions, I change a head of it with some summary:
 - only one camera working in time (due to old isp10 driver);
 - some board have ISP stability issue - maybe frequency too high(still need to evaluate);
 - NanoPi T/M 4 use 30\0.5mm connection and not compatible with similar looking 15\1mm RaspberryPi camera. Other 30\0.5mm 13MP cameras may not be compatible too due to different layout. ( Asus Tinkerboard with the same ISP use RPi cam/cable, ).

More detailed info about RKISP can be found [here](https://github.com/ayaromenok/MD/blob/master/Hardware/RkISP.md) - I will try to update it in case of progress.

original text of issue
> NanoPi M4(Rk3399) have stability issues with V4L with CSI cameras(with USB everything is OK), so gstreamer with specific rkisp required

**Comment by JulesThuillier** [comment]
Hi !
Could you elaborate on the specific rkisp please ?
I have been testing the ov4689 on the Nano Pi M4 today using gstreamer just to display the video, and I could saw those stability issues in the dmesg. I was using FriendlyElec Desktop.
Have you been using it with FriendElec kernel too ? I am trying to get armbian to work with the camera... without much luck so far.

**Comment by ayaromenok** [comment]
Good day!
I had stability issues with FriendlyElec Desktop(2018/12/18) too (dmseg issue, including Error, which stop display\record - below).

Armbian kernel(4.4) include all code for camera - only need to switch it on in config, but I didn't manage to control ISP from system - look like it should be /dev/media device for it, but it missed. Also I didn't manage to build RockChip gstreamer plugins. I will try again next week ;)  

```
[91151.283111] cif_isp10_mipi_isr WARN: CIF_MIPI_ERR_CSI: 0x1100001
[91151.283134] cif_isp10_mipi_isr WARN: CIF_MIPI_SYNC_FIFO_OVFLW: 0x1100001
[91151.316596] cif_isp10_mipi_isr WARN: CIF_MIPI_ERR_CSI: 0x1100001
[91151.316617] cif_isp10_mipi_isr WARN: CIF_MIPI_SYNC_FIFO_OVFLW: 0x1100001
[91151.349906] cif_isp10_mipi_isr WARN: CIF_MIPI_SYNC_FIFO_OVFLW: 0x1
[91151.349943] cif_isp10_mipi_isr WARN: CIF_MIPI_ERR_CSI: 0x1100000
[91151.383399] cif_isp10_mipi_isr WARN: CIF_MIPI_SYNC_FIFO_OVFLW: 0x1
[91151.383419] cif_isp10_mipi_isr(6810) ERR: mipi_mis icr err: 0x1100000
[91151.384026] cif_isp10_mipi_isr WARN: CIF_MIPI_ERR_CSI: 0x1100000
[91151.416829] cif_isp10_mipi_isr WARN: CIF_MIPI_SYNC_FIFO_OVFLW: 0x1
[91151.416880] cif_isp10_mipi_isr WARN: CIF_MIPI_ERR_CSI: 0x1100000
[91151.450278] cif_isp10_mipi_isr WARN: CIF_MIPI_SYNC_FIFO_OVFLW: 0x1
[91151.450331] cif_isp10_mipi_isr WARN: CIF_MIPI_ERR_CSI: 0x1100000
```

**Comment by ayaromenok** [comment]
old info about 6 lines below  belong to only one of RK3399 board. from other hand, Firefly Rk3399 use 4line ov1350 sensor in 2 line mode

> maybe it's a good place to leave some more info:
>  - ov4689 use 4 line CSI;
>  - Nano Pi M/T4 use dual MIPI intefrace with 4 lines each;
>  - Rk3399 have only 6 CSI lines, so for dual-camera mode ov4689 sensor should be configurated with 2 lines (in fact, it's similar to Raspberry PI Compute/dual-camera mode, but RPI cameras originally use 2 line design, so don't required reconfiguration);
>  - this also means, that outstanding video performance of ov4689 cannot be achieved in dual-camera mode too

**Comment by ayaromenok** [comment]
kernel 5.1 merge for Nano pi T/M/Neo 4 support
https://github.com/torvalds/linux/commit/6ad63dec9c2c80710896edd1996e56c54a230870

**Comment by JulesThuillier** [comment]
Hi ! Thanks for the help ! 
I am stumbling on the exact same issues here. I tried to build Armbian with different config all day to get the new isp driver to work (rockchip-isp1 instead of the old rkisp10), but I can't get to see the /dev/media device to control the ISP...
I'll share the info here when I get it to work :)
And great found on the merge notes, 2 days old only :o

**Comment by ayaromenok** [comment]
btw, it's no /dev/media in friendlyelec build too.

**Comment by ayaromenok** [comment]
well, good news is - I manage to get camera working with Armbian
key point - need to use `https://github.com/rockchip-linux/gstreamer-camera` instead of other gsteramer-plugin/plugin-extra repositories.

I will continue my evaluation - since now looks like something with a color, but it works ;) https://github.com/ayaromenok/test/commit/b5b5c0770ac31d65052dce3e0aef174d6c5ac127

**Comment by ayaromenok** [comment]
dmesg show same errors. but looks like camera work a bit more stable (OpenCV camera app not freezing)
```
[ 9081.826426] cif_isp10_mipi_isr(6810) ERR: mipi_mis icr err: 0x2
[ 9081.826443] cif_isp10_mipi_isr WARN: CIF_MIPI_SYNC_FIFO_OVFLW: 0x2
[ 9081.826454] cif_isp10_mipi_isr(6810) ERR: mipi_mis icr err: 0x2
[ 9081.826468] cif_isp10_mipi_isr WARN: CIF_MIPI_SYNC_FIFO_OVFLW: 0x2
[ 9081.826492] cif_isp10_mipi_isr WARN: CIF_MIPI_SYNC_FIFO_OVFLW: 0x2
[ 9081.826494] systemd-journald[312]: /dev/kmsg buffer overrun, some messages lost.
[ 9081.826512] cif_isp10_mipi_isr(6810) ERR: mipi_mis icr err: 0x2
[ 9081.826530] cif_isp10_mipi_isr WARN: CIF_MIPI_SYNC_FIFO_OVFLW: 0x2
[ 9081.826540] cif_isp10_mipi_isr(6810) ERR: mipi_mis icr err: 0x2
[ 9081.826554] cif_isp10_mipi_isr WARN: CIF_MIPI_SYNC_FIFO_OVFLW: 0x2
[ 9081.826578] cif_isp10_mipi_isr WARN: CIF_MIPI_SYNC_FIFO_OVFLW: 0x2
[ 9081.826580] systemd-journald[312]: /dev/kmsg buffer overrun, some messages lost.
```

**Comment by hosaka** [comment]
@ayaromenok Can I ask you what pipeline do you use from opencv to capture camera input? I have a NanoPi NEO4 and i'm struggling to get the ov13850 camera working. I'm attempting to open the VideoCapture with the folloging pipeline passed:
```
rkisp device=/dev/video0 sensor-id=1 io-mode=4 path-iqf=/etc/cam_iq/rk-ov13850.xml ! video/x-raw,format=NV12,width=640,height=480,framerate=30/1 ! appsink
```

But the isOpened always returns false. Any help would be appreciated!

**Comment by ayaromenok** [comment]
@hosaka 
I don't have ov13850 camera (only ov46xx), so it's only theoretical ideas:
 - try to get picture from camera via streamer without OpenCV: `gst-launch-1.0 rkisp device=/dev/video0 sensor-id=1 io-mode=4 path-iqf=/etc/cam_iq/rk-ov13850.xml ! video/x-raw,format=NV12,width=4224,height=3136,framerate=30/1 ! rkximagesink` 
- try to use full sensor resolution - 4224,3136

PS: I use OpenCV 4.0.x, built with gstreamer support and not a FriendlyElec prebuild OpenCV 3.4.x

**Comment by hosaka** [comment]
@ayaromenok Hi, thank you for your reply! I'm also using OpenCV 4.0.1 built with gstreamer. I've got this simple pipeline working:
```
rkisp device=/dev/video0 sensor-id=1 io-mode=4 path-iqf=/etc/cam_iq/rk-ov13850.xml ! video/x-raw,format=NV12,width=640,height=480,framerate=30/1 ! videoconvert ! appsink
```
However this doesn't use the rockchip mpp encoder/decoder. And thus opencv performance suffers between frames, USB camera works much better. Also, I need smaller images on the receiving end, since I'm feeding them into a neural network at the end, so the full resolution is not necessary.

From FriendlyElec wiki (actually the gst-camera.sh script) I can see that h264 encoder/decoder is available (gstreamer-rockchip) 
```
gst-launch-1.0 rkisp num-buffers=512 io-mode=4 path-iqf=/etc/cam_iq/${XMLFILE} \
    ! video/x-raw,format=NV12,width=1280,height=720,framerate=30/1 \
    ! tee name=t t. ! queue ! kmssink t. ! queue ! mpph264enc \
    ! queue ! h264parse ! mpegtsmux ! filesink location=1.ts
```
Resulting files are much smaller than raw capture. Would you happen to have some suggestions on how to use the hardware encoder/decoder to feed compressed data into OpenCv? I'm guessing that this will help with performance.

Cheers!

**Comment by ayaromenok** [comment]
@hosaka - in general - you don't need to use h264 encoder in ISP and than a h264 decoder in OpenCV to get a data, so first option with RAW data(in NV12 format) is correct - no intermediate conversion, except from NV12 to BGR (one more idea - use may Video4Linux directly - and converts to BGR in CV).

The problem is in camera config\software support - while your 13MP sensor support a smaller native resolution (2112x1568 at 60fps), looks like it's always used a full 13MP resolution, and this board just not fast enough for this. Plus, in camera config you may find something like a 7.5 and 15fps for some resolution - this may affect too.

PS: ov46xx sensor (which I have) is looks more suitable for NN - at least it can handle stable 30fps(plus, have wider FOV)

upd: just check rk-ov13850.xml - 2012x1568 is supported, but in 15fps. you can try to use this resolution, than resize to smaller one inside of OpenCV - probably, with a POT(Power of  Two) scale factor to avoid usage of floating-point (4: 528x392 or 8: 264x196 or even smaller) - If I am right, OpenCV use NVidia Carotene NEON library for Arm7/Arm8 for resize operation - which is quite fast. if you don't need color info, drop it too

**Comment by hosaka** [comment]
@ayaromenok Thank you for your suggestions! I'll look into purchasing an OV4689 camera and give that a try as well. If I try to use v4l2 directly, I don't need to compile opencv with gstreamer libs right? That would be ideal if I can drop the gstreamer dependencies, convert to BGR and resize in opencv directly from the camera.

**Comment by ayaromenok** [comment]
@hosaka it's a example of image from V4L2 in OpenCV - https://github.com/ayaromenok/test/blob/master/09_CvGStreamerCam/res/yuv1280x720.png - you may try to use it, but I found it useless.

ov4689 sensor can be better for CV type of application (due to high-speed video mode), but again - software support is terrible as for ov13850 :(

**Comment by KitKatFarrelly** [comment]
hey, I've been attempting to get opencv to stream from the ov4689 that I have connected to my nanopi m4. However, I get gstreamer errors when trying to open the camera. Attempting to open using gstreamer throws 
`GStreamer: Error opening bin: no element "rkisp"

(python:7788): GStreamer-CRITICAL **: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed`
even though I can preview just fine using the gst-launch-1.0 bash command. My videocapture method is 
`cap = cv2.VideoCapture("  rkisp device=/dev/video0 sensor-id=1 io-mode=4 path-iqf=/etc/cam_iq/rk-ov4689.xml ! video/x-raw,format=NV12,width=640,height=480,framerate=30/1 ! videoconvert ! appsink",cv2.CAP_GSTREAMER)`
This is in python, but that shouldn't change how the method works. Any help would be appreciated.

**Comment by ayaromenok** [comment]
@pfarrel84 Looks like you don't have `rkisp` gstreamer module for some reason.

What OS do you use on M4 board? This module exist in FriendlyDesktop/Core since 201812xx version, while missing in Armbian for NanoPi M4/avafinder own Ubuntu build.

You can check presence of this gstreamer module by `gst-inspect-1.0  | grep rk` (you may need to install `gstreamer1.0-tools`)

PS: native proportion of ov4689 sensor is 16:9, so resolutions like 672x380, 1280x720, 1920x1080 can provide less distortion on input image (it can be critical for some OpenCV applications)

**Comment by KitKatFarrelly** [comment]
rkisp is detected when I run gst-inspect-1.0 
`rkisp:  rkisp: Gstreamer Plugin For Rockchip ISP Source`
rkisp works properly when I launch it in the command line as 
`gst-launch-1.0 rkisp device=/dev/video0 sensor-id=1 io-mode=4 path-iqf=/etc/cam_iq/rk-ov4689.xml ! video/x-raw,format=NV12,width=1280,height=720,framerate=30/1 ! rkximagesink`
I'm running lubuntu 16.04 on the 4.4 Kernal.

**Comment by ayaromenok** [comment]
@pfarrel84 
It's really strange than. 

Did you build OpenCV by yourself? is it include gstreamer support for camera? python bindings for all modules?

**Comment by KitKatFarrelly** [comment]
Yeah, I compiled OpenCV 3.4.5 from source. Build information says that gstreamer 0.10.36 is supported
` GStreamer:
      base:                      YES (ver 0.10.36)
      video:                     YES (ver 0.10.36)
      app:                       YES (ver 0.10.36)
      riff:                      YES (ver 0.10.36)
      pbutils:                   YES (ver 0.10.36)`
I have opencv built for both python 2 and 3, I don't know a way of checking to make sure all the modules have python bindings though.
I'm suspecting the issue is that gstreamer 0.10 is being used instead of 1.0, I'll probably try recompiling with gstreamer 1.0 later today and see if that fixes it.

**Comment by ayaromenok** [comment]
@pfarrel84
> I'm suspecting the issue is that gstreamer 0.10 is being used instead of 1.0, I'll probably try recompiling with gstreamer 1.0 later today and see if that fixes it.

it's possible.

just in case - my working configuration include OpenCV 4.0.x with GStreamer 1.0, build in Ubuntu 18.04

**Comment by KitKatFarrelly** [comment]
Hey, I got busy yesterday but here's an update:
I got opencv to work with one ov4689 camera using gstreamer 1.0 instead of 0.10, there are no longer any errors. So that's resolved now!
I was able to get your test code to work for one camera, however i cannot get the dual camera setup working. Is there changes to the xml I need to make or other configurations to be made to resolve this? I saw above that the ov4689 uses 4 CSI lines out of 6 so I'm assuming that's the problem. Anyway, I really appreciate your help with getting this working!

**Comment by ayaromenok** [comment]
@pfarrel84 
It's great to know that camera working!

regarding dual-camera - up-to-date info: it can't work with current  FriendlyElec distro.

Technically - it's 2 different driver for RK3399 in kernel: older(~2017) `isp10` and more recent(since 2018) `isp1`. 
Older driver (that what you can find in FirendlyElec Ubuntu 16.04 and 18.04) support only one device in time - controlled via Video4Linux or gstreamer. Newest driver use kernel Media API and support multiply devices, but it's work-in-progress and not correctly integrated with drivers for ov4689/ov13xxx - cameras for NanoPi M4. May be one day drivers will start to work (I know, that it was done some work on armbian\thinkerboard, which use similar ISP, but different CPU - but can't check right now since I am in vacation ;) ) and than it will be possible to evaluate a dual-cam mode\number of CSI line issue.

**Comment by KitKatFarrelly** [comment]
ah, that's a shame honestly. Oh well, thank you for your help!

**Comment by cafrank** [comment]
Oops.  I bought two ov13850's in the hope of running dual cameras with opencv on the NanoPC-T4 FirendlyElec Ubuntu 18.04: 
gst-launch-1.0 rkisp sensor-id=1 io-mode=4 path-iqf=/etc/cam_iq/rk-ov13850.xml device=/dev/video4
  ! video/x-raw,format=NV12,width=720,height=480,framerate=10/1
  ! videoconvert ! autovideosink
With both cameras connected, but running one at a time, /dev/video0 works, but /dev/video4 is flakey.  (One bright frame then dim)

**Comment by ayaromenok** [comment]
@cafrank 
Dual-camera mode not working with T/M4 with FriendlyElec Unbuntu due to usage of _old_ **isp10** driver. 

Rockchip create a _new_ driver, called **isp1**, but as I know, at present moment it's used only on Asus TinkerBoard(201902 build from asus and, possible, armbian too).

I write some result of my driver investigation [here](https://github.com/ayaromenok/MD/blob/master/Hardware/RkISP.md)

**Comment by cafrank** [comment]
Thank you for the quick info.  I will keep the second camera, and try more stuff in the hope of getting to isp1. I initially had Armbrin on the board, but it did not load the drivers (no /dev/video?), so I moved to Friendly-Ununtu 18.04.

**Comment by ayaromenok** [comment]
@cafrank In Armbian you need to rebuild kernel with isp10/camera driver enabled(sources include all necessary patches) and build gstreamer rksip - but I don't find/made correct IQ driver for camera - so AWB is not working.
 
Armbian maintainer- IgorP - already switch on isp10 in his branch, so soon it will work out-of-the-box (at least, with V4L2).

PS. I will return from my vacation in May and will try again to make dual-mode working ;)

**Comment by JulesThuillier** [comment]
Even by enabling ISP10 when building Armbian kernel I was never able to make the driver work or even see the /dev/video or /dev/media. It's like the option did not do anything (I tried about a month ago)

**Comment by ayaromenok** [comment]
@JulesThuillier  you need to enable **isp1** to have chance to see /dev/media (as I remember, you need to use patches from asus tinkerboard kernel first just to build it). 
**isp10** use old V4L2 only driver, so only /dev/video will appear (but you need to build sensor drives too).

**isp10** and **isp1** - two different drivers, which required 2 different gstreamer plugins and IQ settings files for cameras/sensors ;)

**Comment by JulesThuillier** [comment]
**EDIT:** I had not checked the patch. I'll look into it in the upcoming days and give my feedback :)
**EDIT2:** Couldn't find the Armbian patch.
**EDIT3:** Tried again enabling ISP1 in latest Armbian kernel for nanopi M4, it still does not load (checked dmesg)
@ayaromenok I had enabled it in Armbian (for nanopi M4), but I couldn't see or use it (it wasn't even detected as "installed").
The IQ settings files are the XML files right ?
I'll be looking into latest Armbian and Tinkerboard updates, maybe I'll find a solution there.

**Comment by ayaromenok** [comment]
@JulesThuillier I can send you working kernel config in two weeks, when I will back home.
Bun as I remember, I manually switch everything on with `rkisp` (or rockchip ) and sensor driver (ov4* and ov13*) in .config and build in drivers(using `=y` inf config instead of modules `=m`).

yes, IQ settings is XML, but it support own versioning (see `code_xml_parse_version` on top of XML file).
FriendlyElec distro use version 0.18, while gstreamer driver from rockchip repo( which I manage to build) - 0.17 and they not backward-compatible (at least in AWB section). many more version can exist ;)

**Comment by ayaromenok** [comment]
@JulesThuillier @pfarrel84 @cafrank @hosaka 
Good news first: FriendlyElec publish a [new OS image from 20190511](https://drive.google.com/drive/folders/1gaLKSlIHvqhJ5cASTFGSjJ9XvtgosZFQ), which include "new" **RKISP** and `\dev\media0` & `\dev\media1` devices.

and it's working! (with a number of dmesg errors) :) and not stable too.

upd: I manage to get stereo-mode only once, for 2-3 minutes before board reboot. Other attempts lead to streamer crash/reboot(mostly on CSI1 cam). It would be nice to know, is it local issue of my particular board or general instability.

**Comment by ayaromenok** [comment]
for "old" **rkisp10** driver is 
for CSI1 error is follow
```
cif_isp10_mipi_isr WARN: CIF_MIPI_ERR_CSI: 0x100001
cif_isp10_mipi_isr WARN: CIF_MIPI_SYNC_FIFO_OVFLW: 0x100001
cif_isp10_mipi_isr(6867) ERR: mipi_mis icr err: 0x1
```
for CSI2 error the same, as above
```
[ 9081.826512] cif_isp10_mipi_isr(6810) ERR: mipi_mis icr err: 0x2
[ 9081.826530] cif_isp10_mipi_isr WARN: CIF_MIPI_SYNC_FIFO_OVFLW: 0x2
[ 9081.826540] cif_isp10_mipi_isr(6810) ERR: mipi_mis icr err: 0x2
[ 9081.826554] cif_isp10_mipi_isr WARN: CIF_MIPI_SYNC_FIFO_OVFLW: 0x2
[ 9081.826578] cif_isp10_mipi_isr WARN: CIF_MIPI_SYNC_FIFO_OVFLW: 0x2
```

**Comment by ayaromenok** [comment]
FriendlyElec from 20190511 - new **rkisp1** log

```
[    0.240594] iommu: Adding device ff910000.rkisp1 to group 4
[    0.241176] iommu: Adding device ff920000.rkisp1 to group 5
[    1.383363] rkisp1 ff910000.rkisp1: rkisp1 driver version: v00.01.00
[    1.383941] rkisp1 ff910000.rkisp1: Missing rockchip,grf property
[    1.385698] rkisp1 ff910000.rkisp1: GPIO lookup for consumer vsirq
[    1.385707] rkisp1 ff910000.rkisp1: using device tree for GPIO lookup
[    1.385716] of_get_named_gpiod_flags: can't parse 'vsirq-gpios' property of node '/rkisp1@ff910000[0]'
[    1.385725] of_get_named_gpiod_flags: can't parse 'vsirq-gpio' property of node '/rkisp1@ff910000[0]'
[    1.385731] rkisp1 ff910000.rkisp1: using lookup tables for GPIO lookup
[    1.385739] rkisp1 ff910000.rkisp1: lookup for GPIO vsirq failed
[    1.386026] rkisp1 ff920000.rkisp1: rkisp1 driver version: v00.01.00
[    1.386622] rkisp1 ff920000.rkisp1: Missing rockchip,grf property
[    1.388305] rkisp1 ff920000.rkisp1: GPIO lookup for consumer vsirq
[    1.388313] rkisp1 ff920000.rkisp1: using device tree for GPIO lookup
[    1.388322] of_get_named_gpiod_flags: can't parse 'vsirq-gpios' property of node '/rkisp1@ff920000[0]'
[    1.388330] of_get_named_gpiod_flags: can't parse 'vsirq-gpio' property of node '/rkisp1@ff920000[0]'
[    1.388337] rkisp1 ff920000.rkisp1: using lookup tables for GPIO lookup
[    1.388344] rkisp1 ff920000.rkisp1: lookup for GPIO vsirq failed
```

**Comment by ayaromenok** [comment]
CSI1:
for some reason dmesg hang board
```
rkisp1: MIPI mis error 0x0000001
rkisp1: MIPI mis error 0x0000001
rkisp1: MIPI mis error 0x0001001 << not sure about this

```


CSI2:
```
rkisp1: MIPI mis error 0x0000002
rkisp1: MIPI mis error 0x0000002
rkisp1: MIPI mis error 0x0000002
rkisp1: MIPI mis error 0x0100002
```

**Comment by harandK** [comment]
I tried the latest Friendlycore image, but the following pipeline still does not work when two cameras are connected:

`gst-launch-1.0 rkisp num-buffers=20 device=/dev/video0 io-mode=1 path-iqf=/etc/cam_iq/ov4689.xml !
video/x-raw,format=NV12,width=640,height=480,framerate=10/1
!  jpegenc ! multifilesink location=/tmp/test.jpg`

**Comment by ayaromenok** [comment]
@harandK plz, check `dual-camera.sh` script with FriendlyElec image from 201905XX or later.

**Comment by harandK** [comment]
@ayaromenok `dual-camera.sh` assumes a FriendlyDesktop with an lxsession.

**Comment by ayaromenok** [comment]
@harandK yes. Something with X11 session - since you will have 2 windows from both cameras ;)

**Comment by harandK** [comment]
@ayaromenok basically, I would like to use both cameras in a headless mode with opencv, applying stereomatching etc.

**Comment by ayaromenok** [comment]
@harandK it's up to you. But maybe it's a good idea to develop and debug with X11 and multiply windows/using IDE and than switch to console only/headless mode.

Just don't forget to change last parameter to `appsink` in openCV

**Comment by harandK** [comment]
@ayaromenok The camera which is connected to the MIPI CSI1 connector, provides a distorted image. Even when I switch the cameras. Also the performance is really bad in dual mode. Thanks for your help so far.

**Comment by ayaromenok** [comment]
@harandK I had similar issue with one of MIPI CSI1 - [screenshot](https://github.com/ayaromenok/test/blob/master/09_CvGStreamerCam/res/Screenshot_dist20190511.jpg) - and now it even worse - hang up almost immediately. So, I return to Raspberry Pi Compute/IO Board with dual camera setup and sent stereo-pair via network stream to target(more powerful, than RPi) board.
